#todo: Figure out dasbling session saving - autostarting of script still not working-- disable screen locking --- add banner file
---
- name: Pit Computer Configuration
  hosts: pit

  tasks:
    - name: Set hostname to match inventory
      hostname:
        name: '{{ name }}'

    - name: Update package lists
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install prerequisite software
      become: true
      apt:
        name: 
          - i965-va-driver-shaders
          - mpv
          - firefox-esr
          - wireguard-tools
          - openresolv
          - git
          - pip
          - rsync
          - htop
          - nmon
          - intel-gpu-tools
          - iftop

    - name: Update all packages to their latest version
      become: true
      apt:
        name: "*"
        state: latest


#main stuff
    - name: Install MAPSS prerequisite python packages
      pip:
        name:
          - flask 
          - google-api-python-client 
          - GitPython 
          - configparser

    - name: Install MAPSS
      git:
        repo: 'https://github.com/team5419/MAPSS.git'
        dest: ~/Desktop/MAPSS/

    - name: Transfer MAPSS Configuration
      synchronize:
        src: pitcomputer/MAPSS
        dest: ~/Desktop/

    - name: Transfer video files
      synchronize:
        src: pitcomputer/compDisplay
        dest: ~/Desktop/
        delete: true

    - name: Transfer MPV configuration
      synchronize:
        src: pitcomputer/xfce4-keyboard-shortcuts.xml
        dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml

#ssh stuff
    - name: Transfer sshd Configuration
      become: true
      copy:
        src: pitcomputer/sshd_config
        dest: /etc/ssh/sshd_config

    - name: Transfer ssh banner
      become: true
      copy:
        src: pitcomputer/issue.net
        dest: /etc/issue.net

# boot stuff
    - name: Transfer grub Configuration
      become: true
      copy:
        src: pitcomputer/grub
        dest: /etc/default/grub

# autostart stuff
    - name: Transfer autologin Configuration
      become: true
      copy:
        src: pitcomputer/lightdm.conf
        dest: /etc/lightdm/lightdm.conf

    - name: Transfer autostart script
      copy:
        src: pitcomputer/startup.sh
        dest: ~/Desktop/startup.sh
        mode: +x

    - name: Transfer autostart configuration
      synchronize:
        src: pitcomputer/startup.desktop
        dest: ~/.config/autostart/startup.desktop


# further locking down
#    - name: Transfer shortcut configuration
#      synchronize:
#        src: pitcomputer/mpv.conf
#        dest: ~/.config/mpv/mpv.conf

    - name: Remove lock screen
      become: true
      apt:
        name: light-locker
        state: absent

#vpn stuffs
    - name: Transfer wireguard config file
      become: true
      copy:
        src: wireguard/{{ name }}.conf
        dest: /etc/wireguard/team.conf
        owner: root
        group: root
        mode: '0600'

    - name: enable wireguard tunnel
      become: true
      systemd:
        name: wg-quick@team
        state: started
        enabled: yes
